In [2]:
import pandas as pd
import numpy as np
import torch
import sklearn
import matplotlib
import torchinfo, torchmetrics

# Check PyTorch access (should print out a tensor)
print(torch.randn(3, 3))

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using {device} device")

tensor([[-0.6427,  0.5987,  0.1408],
        [ 0.0400,  0.1497, -0.5809],
        [ 0.9094,  1.3978,  1.3792]])
Using cuda device


In [3]:
scalar = torch.tensor(7)

In [4]:
scalar.shape

torch.Size([])

In [5]:
Matrix = torch.tensor([[7, 8], [9, 10]])
Matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [6]:
Matrix.shape

torch.Size([2, 2])

In [7]:
MyTensor = torch.tensor([[[1, 2, 3], [3, 6, 9], [2, 4, 6]]])
MyTensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 6]]])

In [8]:
MyTensor.ndim

3

In [9]:
random_tensor = torch.rand(3,4)

In [10]:
random_image_size_tensor = torch.rand(size=(3, 256,256)) #height, width, colour
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([3, 256, 256]), 3)

In [11]:
ones = torch.ones(size=(3,4))
ones
ones.dtype

torch.float32

In [12]:
torch.arange(start=0,end=1000,step=77) / 11

tensor([ 0.,  7., 14., 21., 28., 35., 42., 49., 56., 63., 70., 77., 84.])

In [13]:
torch.zeros_like(input=torch.ones(size=(3,4)))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [14]:
float_64_tensor = torch.tensor([0.0, 1.0, 2.0], 
                               dtype=torch.float64, # What device is your tensor on
                               )


In [15]:
float_16_tensor = float_64_tensor.type(torch.float16)

In [16]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
float_32_tensor = torch.tensor([0.0,1.0,2.0],dtype=torch.float32)

int_32_tensor * float_32_tensor

tensor([ 0.,  6., 18.])

### Getting info from tensors

1. datatype, shape, right device : tensor.dtype, tensor.shape, tensor.device


In [17]:

myTensor2 = torch.arange(1000)


In [18]:
%%time
sum = 0
for data in myTensor2 :
    sum += data * data

CPU times: user 50.8 ms, sys: 5.35 ms, total: 56.1 ms
Wall time: 5.58 ms


In [19]:
%%time
torch.matmul(myTensor2, myTensor2)

CPU times: user 772 µs, sys: 70 µs, total: 842 µs
Wall time: 82 µs


tensor(332833500)

In [20]:
myTensor3 = torch.arange(10) * 10

In [21]:
torch.mean(myTensor3.type(torch.float32))

tensor(45.)

In [22]:
myTensor3.argmin()

tensor(0)

In [23]:
myTensor4= torch.rand(size=(3,4))
myTensor4

tensor([[0.2836, 0.9668, 0.4395, 0.9040],
        [0.3528, 0.2690, 0.6851, 0.9972],
        [0.2897, 0.3556, 0.7115, 0.4634]])

In [24]:
myTensor4.argmin()

tensor(5)

### Reshaping, Stacking, Squeezing, Unsqueezing
1. Reshaping - reshapes an input tensor to a defined shape
2. View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
3. Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
4. Squeeze - removes all 1 dimensions from a tensor
5. Unsqueeze - add a 1 dimension to a target tensor
6. Permute - Return a view of the input with dimensions permted (swqpped) in a certain way

In [25]:
x = torch.arange(1,11)
x_reshaped = x.reshape(5,2)
x_reshaped, x_reshaped.shape

(tensor([[ 1,  2],
         [ 3,  4],
         [ 5,  6],
         [ 7,  8],
         [ 9, 10]]),
 torch.Size([5, 2]))

In [27]:
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [29]:
x_stacked = torch.stack([x,x,x],dim=1)
x_stacked

tensor([[ 1,  1,  1],
        [ 2,  2,  2],
        [ 3,  3,  3],
        [ 4,  4,  4],
        [ 5,  5,  5],
        [ 6,  6,  6],
        [ 7,  7,  7],
        [ 8,  8,  8],
        [ 9,  9,  9],
        [10, 10, 10]])

In [36]:
x = torch.zeros(2,1,2,1,2)
x.size()


torch.Size([2, 1, 2, 1, 2])

In [39]:
x_original = torch.rand(size=(1,2,3)) * 100

x_permuted = x_original.permute(2, 0, 1) #shifts axis
x_permuted.shape


torch.Size([3, 128, 256])