In [1]:
import pandas as pd
import numpy as np
import torch

# Check PyTorch access (should print out a tensor)
print(torch.randn(3, 3))

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using {device} device")

tensor([[ 0.6143,  1.0801,  0.3533],
        [-0.4981,  1.7876, -1.6772],
        [-0.9674, -2.0160,  0.3809]])
Using cuda device


In [2]:
scalar = torch.tensor(7)

In [3]:
scalar.shape

torch.Size([])

In [4]:
Matrix = torch.tensor([[7, 8], [9, 10]])
Matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [5]:
Matrix.shape

torch.Size([2, 2])

In [6]:
MyTensor = torch.tensor([[[1, 2, 3], [3, 6, 9], [2, 4, 6]]])
MyTensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 6]]])

In [7]:
MyTensor.ndim

3

In [8]:
random_tensor = torch.rand(3,4)

In [9]:
random_image_size_tensor = torch.rand(size=(3, 256,256)) #height, width, colour
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([3, 256, 256]), 3)

In [10]:
ones = torch.ones(size=(3,4))
ones
ones.dtype

torch.float32

In [11]:
torch.arange(start=0,end=1000,step=77) / 11

tensor([ 0.,  7., 14., 21., 28., 35., 42., 49., 56., 63., 70., 77., 84.])

In [12]:
torch.zeros_like(input=torch.ones(size=(3,4)))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [13]:
float_64_tensor = torch.tensor([0.0, 1.0, 2.0], 
                               dtype=torch.float64, # What device is your tensor on
                               )


In [14]:
float_16_tensor = float_64_tensor.type(torch.float16)

In [15]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
float_32_tensor = torch.tensor([0.0,1.0,2.0],dtype=torch.float32)

int_32_tensor * float_32_tensor

tensor([ 0.,  6., 18.])

### Getting info from tensors

1. datatype, shape, right device : tensor.dtype, tensor.shape, tensor.device


In [16]:

myTensor2 = torch.arange(1000)


In [17]:
%%time
sum = 0
for data in myTensor2 :
    sum += data * data

CPU times: user 36.4 ms, sys: 4.04 ms, total: 40.5 ms
Wall time: 4.03 ms


In [18]:
%%time
torch.matmul(myTensor2, myTensor2)

CPU times: user 658 µs, sys: 61 µs, total: 719 µs
Wall time: 70.6 µs


tensor(332833500)

In [19]:
myTensor3 = torch.arange(10) * 10

In [20]:
torch.mean(myTensor3.type(torch.float32))

tensor(45.)

In [21]:
myTensor3.argmin()

tensor(0)

In [22]:
myTensor4= torch.rand(size=(3,4))
myTensor4

tensor([[0.4731, 0.9037, 0.5839, 0.7154],
        [0.6301, 0.1179, 0.9364, 0.3238],
        [0.3409, 0.9117, 0.6990, 0.8968]])

In [23]:
myTensor4.argmin()

tensor(5)

### Reshaping, Stacking, Squeezing, Unsqueezing
1. Reshaping - reshapes an input tensor to a defined shape
2. View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
3. Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
4. Squeeze - removes all 1 dimensions from a tensor
5. Unsqueeze - add a 1 dimension to a target tensor
6. Permute - Return a view of the input with dimensions permted (swqpped) in a certain way

In [24]:
x = torch.arange(1,11)
x_reshaped = x.reshape(5,2)
x_reshaped, x_reshaped.shape

(tensor([[ 1,  2],
         [ 3,  4],
         [ 5,  6],
         [ 7,  8],
         [ 9, 10]]),
 torch.Size([5, 2]))

In [25]:
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [26]:
x_stacked = torch.stack([x,x,x],dim=1)
x_stacked

tensor([[ 1,  1,  1],
        [ 2,  2,  2],
        [ 3,  3,  3],
        [ 4,  4,  4],
        [ 5,  5,  5],
        [ 6,  6,  6],
        [ 7,  7,  7],
        [ 8,  8,  8],
        [ 9,  9,  9],
        [10, 10, 10]])

In [27]:
x = torch.zeros(2,1,2,1,2)
x.size()


torch.Size([2, 1, 2, 1, 2])

In [28]:
x_original = torch.rand(size=(1,2,3)) * 100

x_permuted = x_original.permute(2, 0, 1) #shifts axis
x_permuted.shape


torch.Size([3, 1, 2])

### Indexing

In [29]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [30]:
x [0][2]

tensor([7, 8, 9])

In [31]:
x[:][0][2]

tensor([7, 8, 9])

In [32]:
x[0,:,1]

tensor([2, 5, 8])

In [33]:
x[0][0][0]

tensor(1)

In [34]:
array = np.arange(1.0,8.0)

In [35]:
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [36]:
torch.cuda.device_count()

4